apiVersion: v1
kind: ServiceAccount
metadata:
  name: roar-user
  namespace: roar-psp
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: roar-policies
spec:
  privileged: false
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: psp:enabled
  namespace: roar-psp
rules:
- apiGroups:
  - extensions
  resourceNames:
  - roar-policies
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: "2020-11-19T23:21:37Z"
  name: roar-editor
  namespace: roar-psp  
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: roar-user
  namespace: roar-psp


