apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
  namespace: policy
spec:
  containers:
  - name: mysql
    image: quay.io/bclaster/roar-db:1.0.0
    ports:
    - name: mysql
      containerPort: 3306
      hostPort: 3306
    env:
      - name: MYSQL_DATABASE
        value: registry
      - name: MYSQL_PASSWORD
        value: admin
      - name: MYSQL_ROOT_PASSWORD
        value: root+1
      - name: MYSQL_USER
        value: admin
      



